tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "tertiary-fixed-dim": "#c9c5ce",
                "on-secondary-fixed": "#211631",
                "inverse-primary": "#d4bbff",
                "surface-container-low": "#f9f1ff",
                "secondary-container": "#ead9fe",
                "error-container": "#ffdad6",
                "on-surface-variant": "#4a4551",
                "surface": "#fef7ff",
                "error": "#ba1a1a",
                "primary": "#6d4ca6",
                "on-tertiary-fixed-variant": "#48464d",
                "secondary-fixed": "#ecdcff",
                "on-tertiary": "#ffffff",
                "surface-container-highest": "#ebddff",
                "on-background": "#231043",
                "inverse-surface": "#38265a",
                "on-error-container": "#93000a",
                "secondary-fixed-dim": "#d0c0e4",
                "surface-container-high": "#f0e3ff",
                "outline": "#7b7482",
                "surface-container-lowest": "#ffffff",
                "on-secondary": "#ffffff",
                "primary-fixed": "#ebdcff",
                "secondary": "#665978",
                "inverse-on-surface": "#f7edff",
                "on-primary-fixed-variant": "#55338d",
                "surface-variant": "#ebddff",
                "on-primary-container": "#492680",
                "on-primary-fixed": "#270058",
                "on-secondary-fixed-variant": "#4d415f",
                "on-primary": "#ffffff",
                "primary-fixed-dim": "#d4bbff",
                "primary-container": "#b794f4",
                "on-error": "#ffffff",
                "background": "#fef7ff",
                "surface-tint": "#6d4ca6",
                "tertiary-container": "#a7a4ad",
                "on-secondary-container": "#6a5d7c",
                "surface-container": "#f4eaff",
                "tertiary-fixed": "#e5e1ea",
                "outline-variant": "#ccc3d2",
                "on-tertiary-container": "#3c3a42",
                "surface-bright": "#fef7ff",
                "on-tertiary-fixed": "#1c1b22",
                "tertiary": "#5f5d65",
                "on-surface": "#231043",
                "surface-dim": "#e4d3ff"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "lg": "48px",
                "xl": "80px",
                "sm": "12px",
                "gutter": "24px",
                "container-max": "1200px",
                "md": "24px",
                "base": "8px",
                "xs": "4px"
            },
            "fontFamily": {
                "h1": ["Plus Jakarta Sans", "sans-serif"],
                "h2": ["Plus Jakarta Sans", "sans-serif"],
                "h3": ["Plus Jakarta Sans", "sans-serif"],
                "body-lg": ["Plus Jakarta Sans", "sans-serif"],
                "body-md": ["Plus Jakarta Sans", "sans-serif"],
                "label": ["Plus Jakarta Sans", "sans-serif"]
            },
            "fontSize": {
                "h1": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800"}],
                "h2": ["32px", {"lineHeight": "1.3", "fontWeight": "700"}],
                "h3": ["24px", {"lineHeight": "1.4", "fontWeight": "700"}],
                "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "500"}],
                "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "label": ["14px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}]
            }
        },
    },
};
